services:
  task-manager-app:

    image: akashvyavharetechbulls/task-manager-app:latest
    container_name: task-manager-app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ep-crimson-voice-at02ibpe.c-9.us-east-1.aws.neon.tech:5432/taskmanager
      - SPRING_DATASOURCE_USERNAME=neondb_owner
      - SPRING_DATASOURCE_PASSWORD=npg_1FIu6TiwZDbz

    ports:
      - "8080:8080" 
