services:
  task-manager-app:

    image: akashvyavharetechbulls/task-manager-app:${IMAGE_TAG:-latest}
    container_name: task-manager-app
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}

    ports:
      - "8080:8080" 
