name: compile-ci 

on:
  pull_request:

jobs:
  complie:
    runs-on: ubuntu-latest

    steps:
      - name: git checkout
        uses: action/checkout@v4

      - name: setup Java
        uses: action/java-setup@v4

      - name: maven verify 
        run: mvn verify
